import sqlite3

# conn = sqlite3.connect('Databases/Posts.db')
# conn = sqlite3.connect('Databases/Logins.db')
# conn = sqlite3.connect('Databases/Profiles.db')
# conn = sqlite3.connect('Databases/Connections.db')
# conn = sqlite3.connect('Databases/Messages.db')
conn = sqlite3.connect('Databases/Analytics.db')
cursor = conn.cursor()
# cursor.execute('CREATE TABLE IF NOT EXISTS Posts (id INTEGER PRIMARY KEY, owner TEXT, users_to TEXT, content TEXT)')
# cursor.execute('DELETE FROM Posts')
# cursor.execute('CREATE TABLE IF NOT EXISTS Logins (username TEXT PRIMARY KEY, password_hash TEXT, password_salt TEXT)')
# cursor.execute('DELETE FROM Logins')
# cursor.execute('CREATE TABLE IF NOT EXISTS Profiles (username TEXT PRIMARY KEY, displayname TEXT, bio TEXT, photoid TEXT)')
# cursor.execute('DELETE FROM Profiles')
# cursor.execute('CREATE TABLE IF NOT EXISTS Connections (username TEXT, user_connected TEXT, isFriend INTEGER, isFollowing INTEGER, PRIMARY KEY (username, user_connected))')
# cursor.execute('DELETE FROM Connections')
# cursor.execute('CREATE TABLE IF NOT EXISTS Messages (id INTEGER PRIMARY KEY, owner TEXT, user_to TEXT, SenderCopy TEXT, RecipientCopy TEXT, time REAL)')
# cursor.execute('DELETE FROM Messages')
cursor.execute('CREATE TABLE IF NOT EXISTS Analytics (id INTEGER PRIMARY KEY, views INTEGER, reactions_encrypted TEXT, average_view_time_encrypted TEXT, star_score REAL, num_ratings INTEGER)')
# cursor.execute('DELETE FROM Analytics')
conn.commit()
conn.close()
